module.exports = {
	"ben": {
		name: "Ben Zhang",
		handle: "ben",
		bio: "<b>Ben</b> is a coder and tinkerer who studies <s>the liberal arts</s> computer science and possibly also other things at the College of William and Mary. He likes procedural generation and worldbuilding and coming up with game mechanics. He dabbles with composition, animation, and graphic design; he's into creative writing and music and tries to draw occasionally; and he likes semicolons too much.",
		gid: "113621138779294945004",
		fid: "lexical.enumeration",
	},
	"danial": {
		name: "Danial Hussain",
		image: "danial.jpg",
		handle: "danial",
		bio: "<b>Danial</b> is a self-proclaimed superhero guru who is training to become Batman. Currently studying computer science and biomedical engineering at the University of Virginia, Danial does applied medical research and organizes volunteer programs with Madison House. In his free time, he reads comics, jams to rap music, and is working through iMDB’s top 250 movies of all time.",
		gid: "115007751350960800869",
		fid: "dhussain101",
	},
	"david": {
		name: "David Lanman",
		handle: "david",
		gid: "116292267178665003696",
		bio: "<b>David</b> is a student at the University of Washington and a Software Development Intern at <a href='https://www.peachd.com'>Peach</a>. He wastes far too much time trying to get good at an illegal mod for a party game, and lets Stack Overflow do his coding for him.",
		fid: "david.lanman.3",
	},
	"ellis": {
		name: "Ellis Tsung",
		handle: "ellis",
		image: "ellis.png",
		bio: "<b>Ellis</b> is studying Computer Science at the University of Virginia. He appreciates modern designs and loves hackathons, mechanical keyboards, and EDM. When he's not using an Intellij IDE, Ellis can be found messing with Photoshop or playing SSB4.",
		gid: "103641117311445875167",
		fid: "ellistsung",
	},
	"kyle": {
		name: "Kyle Herndon",
		handle: "kyle",
		image: "kyle.jpg",
		bio: "<b>Kyle</b> is a Computer Science and Physics double major at University of Illinois at Urbana-Champaign. He enjoys almost everything related computer science and physics, but especially quantum computing and computational physics. In his spare time, he plays video games, swing dances, and plans his quest to take over the world.",
		gid: "116891590650962784089",
		fid: "kyle.herndon.90",
	},	
	"matt": {
		name: "Matthew Savage",
		handle: "matt",
		bio: "<b>Matthew</b> is a Computer Science major at Carnegie Mellon University.  He enjoys studying algorithms and often competes in competitions like Codeforces (<span style='color: #AA00AA; font-weight: 600;'><a class='no-display' href='http://codeforces.com/profile/bluepichu'>bluepichu</a></span>) and TopCoder (<span style='color: #616BD5; font-weight: 600;'><a class='no-display' href='https://www.topcoder.com/members/bluepichu/'>bluepichu</a></span>).  He's also interested in design and spends a lot of his time working on web projects.  When he's not hacking, Matthew enjoys taking Nintendo games far too seriously.",
		image: "matt.jpg",
		gid: "118101641190455409267",
		fid: "thesavagematt",
	},
	"thomas": {
		name: "Thomas Lee",
		handle: "thomas",
		bio: "<b>Thomas</b> is currently a student in CWRU majoring in CS and considering electrical engineering. If you are interested on what Thomas has been up to, here's his github: <a href='https://github.com/tomatocurry1'>github.com/tomatocurry1</a>",
		gid: "111319522899190823570",
		fid: "thomas.lee.944",
	},
	"zach": {
		name: "Zach Wade",
		image: "zach.jpg",
		handle: "zach",
		bio: "<b>Zach</b> is a student of Computer Science at Carnegie Mellon University. He likes hacking, game development, and has an unhealthy love for javascript. He loves competitions, and frequently participates in hackathons and ctfs. ",
		gid: "109335746170550705996",
		fid: "zach.ary.545",
	}
}
